#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM __SmartSlimCore31LinuxBaseImage__
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY ./ /app
ENTRYPOINT ["dotnet", "Leo.Guided.Buy.API.dll"]